SELECT OBJECT_TYPE
	,OBJECT_SCHEMA
	,OBJECT_NAME
FROM (
	SELECT 'TABLE' AS OBJECT_TYPE
		,TABLE_NAME AS OBJECT_NAME
		,TABLE_SCHEMA AS OBJECT_SCHEMA
	FROM information_schema.TABLES
	
	UNION
	
	SELECT 'INDEX[Type:Name:Table]' AS OBJECT_TYPE
		,CONCAT (
			CONSTRAINT_TYPE
			,' : '
			,CONSTRAINT_NAME
			,' : '
			,TABLE_NAME
			) AS OBJECT_NAME
		,TABLE_SCHEMA AS OBJECT_SCHEMA
	FROM information_schema.TABLE_CONSTRAINTS	
	) R
WHERE R.OBJECT_SCHEMA = 'glue';