module.exports = {
    docs: [
        "summary",
        {
            type: 'category',
            label: 'People / Business Partners',
            items: [
                "People_Business_Partners/Overview",
                "People_Business_Partners/Address",
                "People_Business_Partners/Address_Type",
                "People_Business_Partners/Bank_Employee",
                "People_Business_Partners/Business_Partner",
                "People_Business_Partners/Business_Partner_Structure",
                "People_Business_Partners/Business_Partner_To_Person",
                "People_Business_Partners/Business_Partner_To_Person_Relationship_Type",
                "People_Business_Partners/Business_Partner_Type",
                "People_Business_Partners/Business_Partner_Relationship_Type",
                "People_Business_Partners/Citizenship",
                "People_Business_Partners/Citizenship_Type",
                "People_Business_Partners/City",
                "People_Business_Partners/Country",
                "People_Business_Partners/Electronic_Address",
                "People_Business_Partners/Electronic_Address_Type",
                "People_Business_Partners/Employee_To_Organizational_Entity",
                "People_Business_Partners/Employee_To_Organizational_Entity_Type",
                "People_Business_Partners/Legal_Identification",
                "People_Business_Partners/Organization_Entity_To_Business_Partner",
                "People_Business_Partners/Organization_Entity_To_Business_Partner_Type",
                "People_Business_Partners/Organization_Structure",
                "People_Business_Partners/Organizational_Entity",
                "People_Business_Partners/Person",
                "People_Business_Partners/Person_PII",
                "People_Business_Partners/Person_Relation_Type",
                "People_Business_Partners/Person_Relationship",
                "People_Business_Partners/Person_Type",
                "People_Business_Partners/Region",
                "People_Business_Partners/Title",
            ]
        },
        {
            type: 'category',
            label: 'Portfolio / Investment Strategy',
            items: [
                "Portfolio/Overview",
                "Portfolio/Benchmark",
                "Portfolio/Benchmark_Constituent",
                "Portfolio/Book",
                "Portfolio/CMA_Set",
                "Portfolio/CMA_Set_Hierarchy",
                "Portfolio/Currency",
                "Portfolio/Currency_Identifier",
                "Portfolio/Currency_Identifier_Type",
                "Portfolio/Financial_Account",
                "Portfolio/Financial_Account_Type",
                "Portfolio/Investment_Strategy",
                "Portfolio/Node_CMA_Covariance",
                "Portfolio/Node_CMA_RR",
                "Portfolio/Portfolio",
                "Portfolio/Portfolio_Structure",
                "Portfolio/Portfolio_Type",
                "Portfolio/Position",
                "Portfolio/Price",
                "Portfolio/Price_Quote",
                "Portfolio/Product",
                "Portfolio/Product_Hierachy",
                "Portfolio/Restriction",
                "Portfolio/Restriction_Definition",
                "Portfolio/Restriction_Set",
                "Portfolio/Restriction_Set_Hierachy",
                "Portfolio/Restriction_To_Set",
                "Portfolio/Restriction_Type",
                "Portfolio/Risk_Profile",
                "Portfolio/Risk_Type"
            ]
        },
        {
            type: 'category',
            label: 'Instruments / Asset Classifications',
            items: [
                "Instruments/Overview",
                "Instruments/Asset_Classification_Node",
                "Instruments/Asset_Classification_Regime",
                "Instruments/Asset_Classification_Structure",
                "Instruments/Instrument",
                "Instruments/Instrument_Attribute_Definition",
                "Instruments/Instrument_Attribute_Value",
                "Instruments/Instrument_Classification",
                "Instruments/Instrument_Type",
                "Instruments/Instrument_Type_Hierachy"
            ]
        },
        {
            type: 'category',
            label: "Proposals / Orders / Positions",
            items: [
                "Proposition_Order_Transaction/Overview",
                "Proposition_Order_Transaction/Fill",
                "Proposition_Order_Transaction/Investment_Proposition",
                "Proposition_Order_Transaction/Investment_Proposition_Position_Change",
                "Proposition_Order_Transaction/Order",
                "Proposition_Order_Transaction/Order_Completion",
                "Proposition_Order_Transaction/Transaction_Meta_Type",
                "Proposition_Order_Transaction/Transaction_Relation",
                "Proposition_Order_Transaction/Transaction_Type",
                "Proposition_Order_Transaction/Transactions",
            ]
        }
    ]
}
