module.exports = {
    docs: [
        "home",
        "summary",
        {
            type: 'category',
            label: 'People / Partner Relationships',
            items: [
                "BP_People/Address",
                "BP_People/Address_Type",
                "BP_People/Bank_Employee",
                "BP_People/BP-Relationship_Type",
                "BP_People/Business_Partner",
                "BP_People/Business_Partner_Structure",
                "BP_People/Business_Partner_To_Person",
                "BP_People/Business_Partner_To_Person_Relationship_Type",
                "BP_People/Business_Partner_Type",
                "BP_People/Citizenship",
                "BP_People/Citizenship_Type",
                "BP_People/City",
                "BP_People/Country",
                "BP_People/Electronic_Address",
                "BP_People/Electronic_Address_Type",
                "BP_People/Employee_To_OE",
                "BP_People/Employee_To_OE_Type",
                "BP_People/Language",
                "BP_People/Legal_Identification",
                "BP_People/OE_To_BP",
                "BP_People/OE_TO_BP_TYPE",
                "BP_People/Organization_Structure",
                "BP_People/Organizational_Entitiy",
                "BP_People/Person",
                "BP_People/Person_PII",
                "BP_People/Person_Relation_Type",
                "BP_People/Person_Relationship",
                "BP_People/Person_Type",
                "BP_People/Region",
                "BP_People/Role",
                "BP_People/Title",
                "BP_People/User",
                "BP_People/User_To_Role"
            ]
        },
        {
            type: 'category',
            label: 'Portfolio / Financial Account / Investment Strategy',
            items: [
                "Portfolio_Strategy/Asset_Classification_Node",
                "Portfolio_Strategy/Asset_Classification_Regime",
                "Portfolio_Strategy/Benchmark",
                "Portfolio_Strategy/Benchmark_Constituent",
                "Portfolio_Strategy/Book",
                "Portfolio_Strategy/CMA_Set",
                "Portfolio_Strategy/CMA_Set_Hierachy",
                "Portfolio_Strategy/Currency",
                "Portfolio_Strategy/Currency_Identifier",
                "Portfolio_Strategy/Currency_Identifier_Type",
                "Portfolio_Strategy/Financial_Account",
                "Portfolio_Strategy/Financial_Account_Type",
                "Portfolio_Strategy/Investment_Strategy",
                "Portfolio_Strategy/Node_CMA_Covariance",
                "Portfolio_Strategy/Node_CMA_RR",
                "Portfolio_Strategy/Portfolio",
                "Portfolio_Strategy/Portfolio_Structure",
                "Portfolio_Strategy/Portfolio_Type",
                "Portfolio_Strategy/Position",
                "Portfolio_Strategy/Restriction",
                "Portfolio_Strategy/Restriction_Definition",
                "Portfolio_Strategy/Restriction_Set",
                "Portfolio_Strategy/Restriction_Set_Hierachy",
                "Portfolio_Strategy/Restriction_to_Set",
                "Portfolio_Strategy/Restriction_Type",
                "Portfolio_Strategy/Risk_Profile"
            ]
        },
        {
            type: 'category',
            label: 'Instruments / Asset Classifications',
            items: [
                "Instruments_Classification/Asset_Classification_Node",
                "Instruments_Classification/Asset_Classification_Regime",
                "Instruments_Classification/Asset_Classification_Structure",
                "Instruments_Classification/Benchmark",
                "Instruments_Classification/Benchmark_Constituent",
                "Instruments_Classification/Instrument",
                "Instruments_Classification/Instrument__Attribute_Definition",
                "Instruments_Classification/Instrument__Attribute_Value",
                "Instruments_Classification/Instrument_Type_Hierachy"
            ]
        },
        {
            type: 'category',
            label: "Positions / Transactions / Orders/ Investment Propositions",
            items: [
                "Proposition_Order_Transaction/Currency",
                "Proposition_Order_Transaction/Currency_Identifier",
                "Proposition_Order_Transaction/Currency_Identifier_Type",
                "Proposition_Order_Transaction/Fill",
                "Proposition_Order_Transaction/Financial_Account",
                "Proposition_Order_Transaction/Financial_Account_Type",
                "Proposition_Order_Transaction/Investment_Proposition",
                "Proposition_Order_Transaction/Investment_Proposition_Position_Change",
                "Proposition_Order_Transaction/Order",
                "Proposition_Order_Transaction/Order_Completion",
                "Proposition_Order_Transaction/Portfolio",
                "Proposition_Order_Transaction/Portfolio_Type",
                "Proposition_Order_Transaction/Position",
                "Proposition_Order_Transaction/Transaction_Meta_Type",
                "Proposition_Order_Transaction/Transaction_Relation",
                "Proposition_Order_Transaction/Transaction_Type",
                "Proposition_Order_Transaction/Transactions",
            ]
        }


    ]
}
